### ISSUE TITLE
Confirm/correct units and align files to provide the same information

### ISSUE THREAD

**Issue by SnowHydrology** [NOAA-OWP/snow17#18]
## Current behavior

The BMI specification and ForcingType provide different units:
<img width="296" alt="image" src="https://user-images.githubusercontent.com/32177682/183922629-0f7603b6-7653-4814-b0c7-3497280dd229.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/32177682/183922709-3a0e2e98-b6ac-46c8-bf06-ce1ff4d77d13.png">

Additionally, Snow-17 may use implied rates (mm/d) as the model is set to run on a daily timestep. In that vein, Snow-17 estimates melt by multiplying the daily air temperature minus the base air temperature for melt by a melt factor (also known as a degree day factor). A common unit for such factors is mm/d/°C. 

## Expected behavior

The BMI specification and ForcingType need to be aligned and both provide the same, correct units.

**Comment by andywood** [comment]
I changed the forcing & raim output types and adjusted the example input forcings files so that fluxes are rates and air temperature is 'degC' which can be used by ngen.
