### ISSUE TITLE
tailor output formatting to current nextgen practice

### ISSUE THREAD

**Issue by andywood** [NOAA-OWP/snow17#3]
Current output formatting does not necessarily match what is used by other model formulations. Although when run in the ngen framework, the framework will control the output, it may simplify analysis or comparison to other models offline if a standard formatting is used.

**Comment by SnowHydrology** [comment]
@andywood, Can you expand on what you mean for this issue? Are there any specific actions we should consider?

**Comment by andywood** [comment]
Looking back, I think this meant that when converting snow17, I didn't make any attempt to adjust the existing (standalone run) output or its formatting & labeling to match other models that were connected to ngen.  I was probably flagging it as something we might circle back to if needed.  Back then I'm not sure there were any conventions but now there might be.   When run in the framework, that would all be taken care of by the framework output routines.  If standalone mode output seems important, we can look at what other ngen models that run in standalone are doing and decide if we want to emulate that.  It's not hard -- would most likely be adjustments to a few lines of print statements, or perhaps a hash to assign different variable names.  But I'm not sure if it's a desired feature or not.

**Comment by SnowHydrology** [comment]
Got it. You're correct that the framework will handle output when Snow-17 is run in NextGen.

I'll close this now because it's expected that models will rely on their own unique output routines when running in standalone.
