### ISSUE TITLE
Compiler error on Intel Fortran compiler

### ISSUE THREAD

**Issue by drakest123** [NOAA-OWP/snow17#38]
Building Snow-17 (standalone) on a PC in Visual Studio using the Intel Fortran compiler produces an error in updt19.f at line 50:

## Current behavior
`Error #6633: The type of the actual argument differs from the type of dummy argument. [LIQW]`

## Resolution
The error is caused because LIQW is implicitly INTEGER type. This error was fixed by add at line 25 of updt19.f:
`REAL LIQW`

**Comment by SnowHydrology** [comment]
Closed by #43
