### ISSUE TITLE
Runtime error with Intel Fortran compiler

### ISSUE THREAD

**Issue by drakest123** [NOAA-OWP/snow17#39]
Runtime error when reading forcing data when compiled with the Intel Fortran compiler.

## Current behavior
The program fails to read forcing data files and crashes. In file ioModule.f90, subroutine init_forcing_files(), the integer `ios` is not initialized and acquires an unrestricted value with this compiler.

## Resolution
Add at line 175: `ios = 0`

**Comment by SnowHydrology** [comment]
Closed by #43
