### ISSUE TITLE
nexus files are overwritten by NGEN/Snow-17 executable

### ISSUE THREAD

**Issue by drakest123** [NOAA-OWP/snow17#52]
For an NGEN/Snow-17 executable, a nexus file is overwritten when more than one catchment references that nexus id. 

## Current behavior
Executing NGEN/Snow-17 produces a single cat-XX.csv and a single nexus-YY.csv file, where XX refers to the catchment id and YY refers to the nexus id. If a subsequent run on a different catchment refers to the same nexus id, that second nexus file will overwrite the original nexus file. This is a problem particularly because the two versions of nexus files contain different information.

## Expected behavior
There is not a one-to-one correspondence between catchment and nexus ids. Therefore, the expected behavior should be that nexus files have unique identifiers. This would be possible by including the catchment id in the nexus id file name. Having multiple versions at the same nexus would enable post-processing to refine flows across the domain.

## Steps to replicate behavior (include URLs)

1. Execute NGEN/Snow-17 with a catchment and nexus id
2. Execute NGEN/Snow-17 again with a different catchment but the same nexus id as the first run
3. The second execution will overwrite the nexus file

**Comment by hellkite500** [comment]
Why not run both catchments upstream of the nexus simultaneously? e.g.

```sh
ngen hydrfoab.gpkg "cat-1, cat-2" hydrofab.gpkg "nex-1" realization.json
```

ngen aggregates all contributions to a nexus and writes the aggregated flow to the `nex-X.csv` file.  The relevant data to reconstruct should be available in the `cat-X.csv` files if you know which variable is the essential runoff variable (in a ngen realization, this is the `main_output_variable`).  So even if you are testing each one individually as described, you could find that column in the relevant catchment files and sum them together.

**Comment by SnowHydrology** [comment]
Closing this issue because it relates to how NextGen writes nexus files and not how Snow-17 functions.
